services:
  ui:
    image: nikhilllll/chess-ui:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WS_URL=wss://chesss.thecabbro.com/ws
    depends_on:
      - ws
    restart: unless-stopped

  ws:
    image: nikhilllll/chess-ws:latest
    ports:
      - "8080:8080"
    restart: unless-stopped